### PRACTICE ASSIGNMENTS

***Based on california housing dataset answer the Questions that follow.***

In [35]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
features, labels = fetch_california_housing(as_frame = True, return_X_y = True)

Q1. What is the shape of feature matrix for the dataset?

In [36]:
features.shape

(20640, 8)

Q2. How many missing values are present in the dataset?

In [37]:
features.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

***For Que 3 to 6, split the california housing dataset into train and test sets.***

Q3. What is the value of house age in third sample of test set?

In [38]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2, shuffle=False, random_state=0)
features_test['HouseAge']

16512    34.0
16513    17.0
16514    28.0
16515    37.0
16516    18.0
         ... 
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: HouseAge, Length: 4128, dtype: float64

Q4. What is the value of Population in the first sample of training set?

In [39]:
features_train['Population']

0         322.0
1        2401.0
2         496.0
3         558.0
4         565.0
          ...  
16507    1605.0
16508     958.0
16509    1252.0
16510    3006.0
16511    1292.0
Name: Population, Length: 16512, dtype: float64

Q5. What is the mean of output label in training set?

In [40]:
labels_train.mean()

2.02067031310562

Q6. What is the median of output label in test set?

In [41]:
labels_test.median()

2.1475

Q7. If we use StandardScaler for preprocessing and LinearRegression for fitting the model with training set obtained in previous questions, what are the coefficients obtained in the predicted model?

In [42]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

pipe = Pipeline([('std_scaler', StandardScaler()),
                 ('lin_reg', LinearRegression())])

imp = pipe.fit(features_train, labels_train)['lin_reg']
imp.coef_

array([ 0.83817967,  0.12032096, -0.32135834,  0.36456599, -0.00170674,
       -0.04524631, -0.87994217, -0.82634126])

Q8. If we use StandardScaler for preprocessing and LinearRegression for fitting the model with training set used in previous question, what is the bias term predicted by the model?

In [43]:
imp.intercept_

2.020670313105614

### GRADED ASSIGNMENTS

***For all graded questions, split the california housing dataset into train and test sets.***

Q1. If we use StandardScaler for preprocessing and LinearRegression for fitting the model with training set used in previous question, what is the R squared value for predictions obtained using test set features?

In [44]:
pipeline = Pipeline([('std_scaler', StandardScaler()),
                 ('lin_reg', LinearRegression())])

graded_ = pipeline.fit(features_train, labels_train)
graded_.score(features_test, labels_test)

0.660514059153199

Q2. If we use StandardScaler for preprocessing and LinearRegression for fitting the model, what is the root mean squared error value for predictions obtained using test set features?

In [45]:
from sklearn.metrics import mean_squared_error
labels_test_predicted = graded_.predict(features_test)
mse = mean_squared_error(labels_test_predicted, labels_test)
rmse = mse**0.5
rmse

0.7033383507521879

***Split the data into training and test sets with random_state=0, shuffle=False and test_size=0.2 parameters.
Let, y_test= target label in test set of california housing dataset
and y_pred=target labels obtained by the model using X_test
Then compute values of the following evaluation metrics***

In [46]:
from sklearn.metrics import explained_variance_score, max_error, mean_absolute_error, mean_squared_error
chd = fetch_california_housing()
X_train, X_test, y_train, y_test = train_test_split(chd.data, chd.target, test_size = 0.2, shuffle = False, random_state = 0)
model = pipeline.fit(X_train, y_train)

Q3. Explained Variance score

In [47]:
explained_variance_score(y_test, model.predict(X_test))

0.6605500501742704

Q4. Max Error

In [48]:
max_error(y_test, model.predict(X_test))

7.260453292958351

Q5. Mean Absolute Error

In [49]:
mean_absolute_error(y_test, model.predict(X_test))

0.5168526993787043

Q6. Mean Squared Error

In [50]:
mean_squared_error(y_test, model.predict(X_test))

0.49468483563880744

***For Ques 7 to 8, perform SGD Regression on the given (scaled using StandardScalar()) dataset, using default hyperparameters and random_state=0.***

Q7. What is the bias term?

In [51]:
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

pipeline = Pipeline([('std_scaler', StandardScaler()),
                     ('sgd_reg', SGDRegressor(random_state=0))])

pipeline.fit(features_train, labels_train)
pipeline['sgd_reg'].intercept_

array([2.01123921])

Q8. What are the coefficients in predicted model?

In [52]:
pipeline['sgd_reg'].coef_

array([ 0.84046697,  0.112331  , -0.41213039,  0.21595971, -0.01781887,
       -0.01480892, -0.87394103, -0.83913104])